### PR TITLE
Implement subscribe command

### PR DESCRIPTION
**Pull request by normanjoyner**
Add ability to subscribe to changes which occur in myriad-kv

@nicktate

### CODE REVIEW

**Comment by nicktate** [comment]
@normanjoyner don't you need to remove subscribers from the array when they exit

**Comment by normanjoyner** [comment]
yes they are removed in the `on_exit` function but i'm going to update to make it cleaner since I changed the way it was working since initially implementing

**Comment by nicktate** [comment]
whoops completely missed that `on_exit`

**Comment by nicktate** [comment]
👍

**Pull request merged**
